[package]
name = "rustlang-base-structure"
version = "0.1.0"
authors = ["vuphu <vuphu.itus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.130", features = ["derive"] }
async-trait = "0.1.51"
uuid = { version = "0.8", features = ["v4"] }