[package]
name = "rustlang-base-structure"
version = "0.1.0"
authors = ["vuphu <vuphu.itus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.130", features = ["derive"] }
async-trait = "0.1.51"
uuid = { version = "0.8", features = ["v4"] }
diesel = "1.4.8"
dotenv = "0.15.0"
err-derive = "0.3.0"
futures = "0.3.18"
once_cell = "1.8.0"

[dependencies.mongodb]
version = "2.0.0"
default-features = false
features = ["async-std-runtime"]