version: '3.3'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - network
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - data-volume:/data/db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    networks:
      - network
networks:
  network:
volumes:
  data-volume: