version: '3.3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
volumes:
  data-volume: